version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run:
          name: Install tools
          command: |
            make -s install-tools
      - restore_cache:
          name: Restore module caches
          keys:
            - go-mod-{{ checksum "go.sum" }}
            - go-mod-
      - run:
          name: Download modules
          command: make -s mod-download
      - save_cache:
          name: Save module caches
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Check fmt difference
          command: make -s fmt-diff
      - run:
          name: Run ci-lint
          command: make -s ci-lint
      - run:
          name: Run lint
          command: make -s lint
      - run:
          name: Run vet
          command: make -s vet
      - run:
          name: Test
          command: make -s test

workflows:
  version: 2
  test:
    jobs:
      - test
